name: Conditional Package and Release

on:
  push:
    branches:
      - main

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Zip the app folder
      run: zip -r app.zip app

    - name: Extract version from package.json
      run: echo "PACKAGE_VERSION=$(cat app/package.json | jq -r .version)" >> $GITHUB_ENV

    - name: Check for 'update' in commit message
      id: check_message
      run: |
        if echo "${{ github.event.head_commit.message }}" | grep -q "update"; then
          echo "UPDATE_DETECTED=true" >> $GITHUB_ENV
        else
          echo "UPDATE_DETECTED=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: env.UPDATE_DETECTED == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: Release ${{ env.PACKAGE_VERSION }}
        draft: false
        prerelease: false

    - name: Upload app.zip to Release
      if: env.UPDATE_DETECTED == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app.zip
        asset_name: app.zip
        asset_content_type: application/zip
