name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # 打包app文件夹为app.zip
    - name: Zip the app folder
      run: zip -r app.zip app

    # 提取package.json中的版本号
    - name: Get version from package.json
      id: package_version
      run: echo "::set-output name=version::$(jq -r .version app/package.json)"

    # 检查标签是否存在
    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse refs/tags/v${{ steps.package_version.outputs.version }} >/dev/null 2>&1; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi

    # 上传ZIP文件到现有发布标签
    - name: Upload ZIP to Existing Release
      uses: actions/upload-release-asset@v1
      if: steps.check_tag.outputs.exists == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/username/repo/releases/tags/v${{ steps.package_version.outputs.version }}
        asset_path: ./app.zip
        asset_name: app.zip
        asset_content_type: application/zip
