name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # 打包app文件夹为app.zip
    - name: Zip the app folder
      run: zip -r app.zip app

    # 提取package.json中的版本号
    - name: Get version from package.json
      id: package_version
      run: echo "::set-output name=version::$(jq -r .version app/package.json)"

    # 检查标签是否存在
    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse refs/tags/v${{ steps.package_version.outputs.version }} >/dev/null 2>&1; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi
    
    # 如果标签不存在，上传app.zip到新标签
    - name: Create new tag
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        git config --local user.email "
        git config --local user.name "
        git tag v${{ steps.package_version.outputs.version }}
        git push origin v${{ steps.package_version.outputs.version }}
        gh release create v${{ steps.package_version.outputs.version }} app.zip --title "v${{ steps.package_version.outputs.version }}" --notes "v${{ steps.package_version.outputs.version }}"
        
    # 如果标签存在，上传app.zip更新标签
    - name: Update existing tag
      if: steps.check_tag.outputs.exists == 'true'
      run: |
        git config --local user.email "
        git config --local user.name "
        git tag -f v${{ steps.package_version.outputs.version }}
        git push -f origin v${{ steps.package_version.outputs.version }}
        gh release upload v${{ steps.package_version.outputs.version }} app.zip --clobber
