name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # 打包app文件夹为app.zip
    - name: Zip the app folder
      run: zip -r app.zip app

    # 提取package.json中的版本号
    - name: Get version from package.json
      id: package_version
      run: echo "::set-output name=version::$(jq -r .version app/package.json)"

    